# Configuration File for Evaluation Script, look up ws, ss, k, d in corresponding experiment log file for experiment validation reconstruction

# DEVICE
device: "cpu"

# BATCH SIZE
batch_size: 40

# MODEL FROM
from_save_description: "XXXIII"
from_epoch: 20


# FIRST SKEWNESS PARAMETER FOR SCHEDULER
k: 1.2
# Second skewness parameter for scheduler
d: 0.8


# WHETHER TO RETRIEVE SAMPLE BATCH (NON-) DETERMINISTICALLY
shuffle: True
